services:
  events-service:
    build: ./events-service
    ports:
      - "${EVENTS_SERVICE_PORT}:${EVENTS_SERVICE_PORT}"
    volumes:
      - ./events-service/target:/events-service/target
    env_file:
      - .env
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true

  notifications-service:
    build: ./notifications-service
    ports:
      - "${NOTIFICATIONS_SERVICE_PORT}:${NOTIFICATIONS_SERVICE_PORT}"
    volumes:
      - ./notifications-service/target:/notifications-service/target
    env_file:
      - .env
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true

  ticketing-service:
    build: ./ticketing-service
    ports:
      - "${TICKETING_SERVICE_PORT}:${TICKETING_SERVICE_PORT}"
    volumes:
      - ./ticketing-service/target:/ticketing-service/target
    env_file:
      - .env
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env