server {
    listen 8080;
    server_name localhost;

    location /swagger/ {
        rewrite ^/swagger/(.*)$ /$1 break;
        proxy_pass http://localhost;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}