spring.application.name=ticketing-service
server.port=${TICKETING_SERVICE_PORT:8083}

# Database configuration
spring.datasource.url=${DB_URL:jdbc:h2:mem:ticketdb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# H2 Console
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=${H2_CONSOLE_PATH:/h2-console}

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

# Payments Service Configuration
payments.service.url=http://${PAYMENTS_SERVICE_HOST:payments-service}:${PAYMENTS_SERVICE_PORT:8084}/
events.service.url=http://${EVENTS_SERVICE_HOST:events-service}:${EVENTS_SERVICE_PORT:8081}/