apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: eventhub
spec:
  selector:
    app: notification_app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080