apiVersion: apps/v1 #Specifies the Kubernetes API version

kind: Deployment #Defines the the type of Kubernetes resource
metadata:
  name: event-app #name of deployment
  namespace: eventhub
spec: #spec of deployment
  replicas: 3 #amount of replicas
  selector: #defines which app to use
    matchLabels:
      app: Event_app #defines the labelselector used by the deployer to identify and manage this deployment
  template:
    metadata:
      labels:
        app: Event_app # Applies the label to the pods created by this Deployment.
    spec: #defines the pods
      containers: # a pod and its configurations
        - name: event-backend #name
          image: events-service:latest   #image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 #port
          envFrom:
            - configMapRef:
                name: service-ports


---

apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: eventhub
spec:
  selector:
    app: Event_app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: event-route
  namespace: eventhub
spec:
  hosts:
    - "*"
  gateways:
    - eventhub-gateway
  http:
    - match:
          - uri:
              prefix: /events/swagger-ui.html
      route:
        - destination:
            host: events-service  # Routes to this service
            port:
              number: 8080


    - match:
        - uri:
            prefix: /events
      route:
        - destination:
            host: events-service  # Routes to this service
            port:
              number: 8080


